void deleteArr(int* sum_results, int col);
int newSize(int* sum_results, int col);
int* newArr(int* sum_results, int col);
void raz(int* x);
int** init_matrix_NxM(int col, int row);
int** paste_NxM(int** arr, int row, int col);
void print_matrix(int row, int col, int** arr);
int* arrayM2(int* sum_results, int col);
void arraysum(int* sum_results, int row, int col, int** arr);
void output2(int* sum_results, int col);
void quickSort(int* arr, int down, int up);
int* sumResult(int col, int row, int* sum_results, int** array);
void quickSortMatrix( int**& arr, int row, int col);
int* init_array(int x);
void freee(int**& array, int row, int* sum_results);
void free(int**& array, int row, int* sum_results);