void deleteArr(int* sumResults, int col);
int newSize(int* sumResults, int col);
int* newArr(int* sumResults, int col);
void raz(int* x);
int** initMatrixNxM(int col, int row);
int** pasteNxM(int** arr, int row, int col);
void printMatrix(int row, int col, int** arr);
int* arrayM2(int* sumResults, int col);
void arraySum(int* sumResults, int row, int col, int** arr);
void output2(int* sumResults, int col);
void quickSort(int* arr, int down, int up);
int* sumResult(int col, int row, int* sumResults, int** array);
void quickSortMatrix( int**& arr, int row, int col);
int* initArray(int x);
