int checkInputInt();
void mainMenu();
void theFirstTask();
void theSecondTask();
int menu();
char* getstr(char*);
int str_len(char*);
char* removeExtraSpaces(char*);
char* insertStrings(char*, char*, int, int);
char* allocateMemory(char* string);